// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1alJu89hi4Dp0sFu-RebryRLjCSDuKhg',
    appId: '1:362219956591:web:4ecafa9cafa0086616609a',
    messagingSenderId: '362219956591',
    projectId: 'timodesk',
    authDomain: 'timodesk.firebaseapp.com',
    storageBucket: 'timodesk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOS3OIPpxFCO1GN_xNfC9RPxpzNkCtpM',
    appId: '1:362219956591:android:cebb21a5ab1d5e6916609a',
    messagingSenderId: '362219956591',
    projectId: 'timodesk',
    storageBucket: 'timodesk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplQw9P6Jyky547VPEYwu_XlGlok0kdUU',
    appId: '1:362219956591:ios:c4a317fb7e869c7c16609a',
    messagingSenderId: '362219956591',
    projectId: 'timodesk',
    storageBucket: 'timodesk.firebasestorage.app',
    iosBundleId: 'com.example.timoAdmin',
  );
}
